In [1]:
""" 
examine why brd list contents didn't all match up to
SEC > 100M  annual reports


2019 SEC filings with 2020 bankruptcies
"""

" examine why brd list contents didn't all match up t\nSEC > 100M  annual reports"

In [36]:
import psycopg2 as pg
import pandas.io.sql as pd_sql
import pandas as pd
import numpy as np
import datetime

In [37]:
# Postgres info to connect

connection_args = {
    'host': 'localhost',  
    'dbname': 'bankruptcy',  
    'port': 5432          
}

connection = pg.connect(**connection_args)
connection.autocommit = True

In [38]:
# few fields for first initial model
# all 2019 data held out for test set

query = """
SELECT *
FROM sec_prep_2019
;
"""

sec_data = pd_sql.read_sql(query, connection)
sec_data.head()

,company_name,period_end_date,number_of_quarters,submission_number,central_index_key,ein,sic,fiscal_year_end,fiscal_year,form,...,InterestExpense,InventoryNet,SalesRevenueGoodsNet,WorkingCapital,Revenue_any,SIC Code,Industry,Unnamed: 2,div_code,Division
0,1 800 FLOWERS COM INC,2019-06-30,4,0001437749-19-018360,1084869,113117311,5990,630.0,2019,10-K,...,NaN,NaN,NaN,NaN,NaN,5990,"Retail-Retail Stores, NEC",None,59,Retail Trade
1,"10X GENOMICS, INC.",2019-12-31,4,0001193125-20-052640,1770787,455614458,3826,NaN,2019,10-K,...,2.099667e+06,11920000.0,NaN,NaN,1.544303e+08,3826,Laboratory Analytical Instruments,None,38,Manufacturing
2,"1347 PROPERTY INSURANCE HOLDINGS, INC.",2019-12-31,4,0001493152-20-005206,1591890,461119100,6331,NaN,2019,10-K,...,NaN,NaN,NaN,NaN,NaN,6331,"Fire, Marine & Casualty Insurance",None,63,"Finance, Insurance and Real Estate"
3,"1895 BANCORP OF WISCONSIN, INC.",2019-12-31,4,0001564590-20-014188,1751692,000000000,6036,NaN,2019,10-K,...,4.583000e+06,NaN,NaN,NaN,NaN,6036,"Savings Institutions, Not Federally Chartered",None,60,"Finance, Insurance and Real Estate"
4,1LIFE HEALTHCARE INC,2019-12-31,4,0001564590-20-013666,1404123,760707204,8011,NaN,2019,10-K,...,7.040000e+05,3521500.0,NaN,NaN,NaN,8011,Services-Offices & Clinics of Doctors of Medicine,None,80,Services

In [39]:
company_unique = pd.DataFrame(sec_data['company_name'].unique(), columns={'Name'})

In [40]:
company_unique = set(sec_data['company_name'].unique())
company_unique

{'IDACORP INC',
 'WAYSIDE TECHNOLOGY GROUP, INC.',
 'KBS REAL ESTATE INVESTMENT TRUST II, INC.',
 'FACTSET RESEARCH SYSTEMS INC',
 'CABOT MICROELECTRONICS CORP',
 'UNITED INSURANCE HOLDINGS CORP.',
 'HALOZYME THERAPEUTICS, INC.',
 'TRACTOR SUPPLY CO /DE/',
 'NATIONAL CINEMEDIA, INC.',
 'RESOURCE REAL ESTATE OPPORTUNITY REIT, INC.',
 'PRIMEENERGY RESOURCES CORP',
 'UNIVERSAL HEALTH REALTY INCOME TRUST',
 'SCHNEIDER NATIONAL, INC.',
 'WHITING PETROLEUM CORP',
 'FIESTA RESTAURANT GROUP, INC.',
 'MARTEN TRANSPORT LTD',
 'UNITED STATES STEEL CORP',
 'INDEPENDENT BANK CORP /MI/',
 'CIMPRESS N.V.',
 'MANNING & NAPIER, INC.',
 'MESA AIR GROUP INC',
 'LENDINGTREE, INC.',
 'VIRTU FINANCIAL, INC.',
 'STANDEX INTERNATIONAL CORP/DE/',
 'NORTHWESTERN CORP',
 'ENERGY 11, L.P.',
 'MOSAIC CO',
 'BARNES & NOBLE EDUCATION, INC.',
 'ACELRX PHARMACEUTICALS INC',
 'EDWARDS LIFESCIENCES CORP',
 'RPT REALTY',
 'YEXT, INC.',
 'TITAN MACHINERY INC.',
 'MUELLER INDUSTRIES INC',
 'DIAMOND OFFSHORE DRILLING, INC.',
 'THERAPEUTICSMD, INC.',
 'FIRST NORTHERN COMMUNITY BANCORP',
 'GMS INC.',
 'WISCONSIN PUBLIC SERVICE CORP',
 'VALERO ENERGY CORP/TX',
 'AMAG PHARMACEUTICALS, INC.',
 'CEVA INC',
 'ALCOA CORP',
 'WASHINGTON PRIME GROUP INC.',
 'LOWES COMPANIES INC',
 'PB BANCORP, INC.',
 'UNIT CORP',
 'COMCAST CORP',
 'PING IDENTITY HOLDING CORP.',
 'RYMAN HOSPITALITY PROPERTIES, INC.',
 'CIENA CORP',
 'ABIOMED INC',
 'COOPER-STANDARD HOLDINGS INC.',
 'FLUIDIGM CORP',
 'STARRETT L S CO',
 'PHATHOM PHARMACEUTICALS, INC.',
 'ATN INTERNATIONAL, INC.',
 'POPE RESOURCES LTD PARTNERSHIP',
 'FNCB BANCORP, INC.',
 'ENTEGRIS INC',
 'GULFPORT ENERGY CORP',
 'MARCHEX INC',
 'SANMINA CORP',
 'CBM BANCORP, INC.',
 'I3 VERTICALS, INC.',
 'WASHINGTON GAS LIGHT CO',
 'LIBERTY OILFIELD SERVICES INC.',
 'CYTOMX THERAPEUTICS, INC.',
 'MEREDITH CORP',
 'POLARIS INC.',
 'JEFFERIES FINANCIAL GROUP INC.',
 'MODERN MEDIA ACQUISITION CORP.',
 'SWITCHBACK ENERGY ACQUISITION CORP',
 'APERGY CORP',
 'GERMAN AMERICAN BANCORP, INC.',
 'PARK NATIONAL CORP /OH/',
 'GRIFFIN INDUSTRIAL REALTY, INC.',
 'CERUS CORP',
 'LAMAR ADVERTISING CO/NEW',
 '1LIFE HEALTHCARE INC',
 'WORLD ACCEPTANCE CORP',
 'ALLIANCEBERNSTEIN HOLDING L.P.',
 'AT&T INC.',
 'PARK HOTELS & RESORTS INC.',
 'GULF ISLAND FABRICATION INC',
 'HENNESSY ADVISORS INC',
 'COMMUNITY FINANCIAL CORP /MD/',
 'GORMAN RUPP CO',
 'DEXCOM INC',
 'V F CORP',
 'SHERWIN WILLIAMS CO',
 'ESTEE LAUDER COMPANIES INC',
 'LILIS ENERGY, INC.',
 'ZAGG INC',
 'SS&C TECHNOLOGIES HOLDINGS INC',
 'UROVANT SCIENCES LTD.',
 'FORTRESS BIOTECH, INC.',
 'GRANITESHARES GOLD TRUST',
 'PAR PACIFIC HOLDINGS, INC.',
 'PERFORMANT FINANCIAL CORP',
 'S&W SEED CO',
 'HD SUPPLY HOLDINGS, INC.',
 'BIOMARIN PHARMACEUTICAL INC',
 'FMC CORP',
 'PROVIDENCE SERVICE CORP',
 'CRESCENT ACQUISITION CORP',
 'FIRSTCASH, INC',
 "TILLY'S, INC.",
 'BIG 5 SPORTING GOODS CORP',
 'HEMISPHERE MEDIA GROUP, INC.',
 'UNIVERSAL FOREST PRODUCTS INC',
 'CRIMSON WINE GROUP, LTD',
 'BROWN FORMAN CORP',
 'REGIONS FINANCIAL CORP',
 'PBF HOLDING CO LLC',
 'ENB FINANCIAL CORP',
 'BOOZ ALLEN HAMILTON HOLDING CORP',
 'SILVERCREST ASSET MANAGEMENT GROUP INC.',
 'RED LION HOTELS CORP',
 'BALL CORP',
 'AMEREN CORP',
 'DESIGNER BRANDS INC.',
 'QUOTIENT TECHNOLOGY INC.',
 'FARMER BROTHERS CO',
 'ULTRAGENYX PHARMACEUTICAL INC.',
 'USD PARTNERS LP',
 'ABERDEEN STANDARD GOLD ETF TRUST',
 'ACTIVISION BLIZZARD, INC.',
 'ELI LILLY & CO',
 'SPECTRUM BRANDS HOLDINGS, INC.',
 'INTELLIA THERAPEUTICS, INC.',
 'APELLIS PHARMACEUTICALS, INC.',
 'CHASE CORP',
 'TRUSTCO BANK CORP N Y',
 'RED ROCK RESORTS, INC.',
 'CONTINENTAL RESOURCES, INC',
 'CHEGG, INC',
 'GENESIS HEALTHCARE, INC.',
 'GREENHILL & CO INC',
 'STONEMOR INC.',
 'QUANTA SERVICES, INC.',
 'BRANDYWINE REALTY TRUST',
 'BANCORP 34, INC.',
 'PERMA-PIPE INTERNATIONAL HOLDINGS, INC.',
 'CHICKEN SOUP FOR THE SOUL ENTERTAINMENT, INC.',
 'KAMAN CORP',
 'RHINO RESOURCE PARTNERS LP',
 'STANDARD DIVERSIFIED INC.',
 'BIO-RAD LABORATORIES, INC.',
 'ZENDESK, INC.',
 'GREAT SOUTHERN BANCORP, INC.',
 'AMPHENOL CORP /DE/',
 'CYTOKINETICS INC',
 'AMN HEALTHCARE SERVICES INC',
 'CONSOLIDATED TOMOKA LAND CO',
 'QUANTERIX CORP',
 'CAPRI HOLDINGS LTD',
 'GAP INC',
 'LINCOLN NATIONAL CORP',
 'IMMUNOGEN, INC.',
 'WALGREENS BOOTS ALLIANCE, INC.',
 'CAMBRIDGE BANCORP',
 'CARETRUST REIT, INC.',
 'HEALTHCARE SERVICES GROUP INC',
 'IDEAYA BIOSCIENCES, INC.',
 'AMERICOLD REALTY TRUST',
 'MARINEMAX INC',
 'U.S. SILICA HOLDINGS, INC.',
 'PARK OHIO HOLDINGS CORP',
 'BURLINGTON NORTHERN SANTA FE, LLC',
 'ADVANCED ENERGY INDUSTRIES INC',
 'CIIG MERGER CORP.',
 'IES HOLDINGS, INC.',
 'AXCELIS TECHNOLOGIES INC',
 'PACIFIC PREMIER BANCORP INC',
 'QUEST DIAGNOSTICS INC',
 'SM ENERGY CO',
 'TAILORED BRANDS INC',
 'TITAN INTERNATIONAL INC',
 'ARROW FINANCIAL CORP',
 'VAIL RESORTS INC',
 'INTRA-CELLULAR THERAPIES, INC.',
 'FRONTIER COMMUNICATIONS CORP',
 'GRACO INC',
 'DIGITAL REALTY TRUST, INC.',
 'U.S. WELL SERVICES, INC.',
 'PANHANDLE OIL & GAS INC',
 'TACTILE SYSTEMS TECHNOLOGY INC',
 'REX AMERICAN RESOURCES CORP',
 'TIAA REAL ESTATE ACCOUNT',
 'AMERICAN FINANCIAL GROUP INC',
 'ALLSCRIPTS HEALTHCARE SOLUTIONS, INC.',
 'GRIFFON CORP',
 'PGT INNOVATIONS, INC.',
 'PRUDENTIAL ANNUITIES LIFE ASSURANCE CORP/CT',
 'LIQUIDITY SERVICES INC',
 'MERIDIAN BIOSCIENCE INC',
 'GALERA THERAPEUTICS, INC.',
 'GLADSTONE COMMERCIAL CORP',
 'HORNBECK OFFSHORE SERVICES INC /LA',
 'J CREW GROUP INC',
 'CLOUDFLARE, INC.',
 'GENESCO INC',
 'HERITAGE FINANCIAL CORP /WA/',
 'SYSTEMAX INC',
 'ASURE SOFTWARE INC',
 'ESCO TECHNOLOGIES INC',
 'TABULA RASA HEALTHCARE, INC.',
 'DAKTRONICS INC /SD/',
 'TELEFLEX INC',
 'ARC DOCUMENT SOLUTIONS, INC.',
 'DUPONT DE NEMOURS, INC.',
 'MARCUS CORP',
 'BRINKS CO',
 'ST JOE CO',
 'BANK OF THE JAMES FINANCIAL GROUP INC',
 'C. H. ROBINSON WORLDWIDE, INC.',
 'U S PHYSICAL THERAPY INC /NV',
 'KIMBALL INTERNATIONAL INC',
 'BRIGHTVIEW HOLDINGS, INC.',
 'FEDERAL HOME LOAN BANK OF CHICAGO',
 'OVINTIV INC.',
 'VIVUS INC',
 'FORTERRA, INC.',
 'EHEALTH, INC.',
 'PINNACLE FINANCIAL PARTNERS INC',
 'KILROY REALTY CORP',
 'BUILDERS FIRSTSOURCE, INC.',
 'DELMAR BANCORP',
 'ALTUS MIDSTREAM CO',
 'SUNPOWER CORP',
 'HORTON D R INC /DE/',
 'GLACIER BANCORP, INC.',
 'JOHNSON OUTDOORS INC',
 'FOSSIL GROUP, INC.',
 'GENERAL FINANCE CORP',
 'STARBUCKS CORP',
 'SERVICEMASTER GLOBAL HOLDINGS INC',
 'GRAF INDUSTRIAL CORP.',
 'ARMOUR RESIDENTIAL REIT, INC.',
 'CASA SYSTEMS INC',
 'SUNNOVA ENERGY INTERNATIONAL INC.',
 'SECURITY NATIONAL FINANCIAL CORP',
 'SUPERNUS PHARMACEUTICALS, INC.',
 'XBIOTECH INC.',
 'READY CAPITAL CORP',
 'NATIONAL VISION HOLDINGS, INC.',
 'BIOHAVEN PHARMACEUTICAL HOLDING CO LTD.',
 'ALLEGIANCE BANCSHARES, INC.',
 'NEWMARK GROUP, INC.',
 'COMPASS DIVERSIFIED HOLDINGS',
 'IQVIA HOLDINGS INC.',
 'TRAVELERS COMPANIES, INC.',
 'ANIXTER INTERNATIONAL INC',
 'MERIDA MERGER CORP. I',
 "MACY'S, INC.",
 'MONARCH CASINO & RESORT INC',
 'EASTERLY GOVERNMENT PROPERTIES, INC.',
 'UNIVERSAL ELECTRONICS INC',
 'HARVARD BIOSCIENCE INC',
 'CIVISTA BANCSHARES, INC.',
 'HIGHLANDS REIT, INC.',
 'TRIUMPH GROUP INC',
 'AMAZON COM INC',
 'BIOTELEMETRY, INC.',
 'SOUTHERN CO',
 'CDW CORP',
 'EVELO BIOSCIENCES, INC.',
 'CRESTWOOD EQUITY PARTNERS LP',
 'CADENCE BANCORPORATION',
 'ORMAT TECHNOLOGIES, INC.',
 'HBT FINANCIAL, INC.',
 'HOME BANCSHARES INC',
 'UNITIL CORP',
 'S&T BANCORP INC',
 'AMERICAN PUBLIC EDUCATION INC',
 'LEE ENTERPRISES, INC',
 'VALLEY NATIONAL BANCORP',
 'SCHLUMBERGER LIMITED/NV',
 'RUSH ENTERPRISES INC TX',
 'SOUTHWEST AIRLINES CO',
 'OCEANFIRST FINANCIAL CORP',
 'KNOLL INC',
 'PPL CORP',
 'CALIFORNIA RESOURCES CORP',
 'TFS FINANCIAL CORP',
 'IRON MOUNTAIN INC',
 'SAFEHOLD INC.',
 'ARES MANAGEMENT CORP',
 'INVESCO DB COMMODITY INDEX TRACKING FUND',
 'SPIRE INC',
 'ALARM.COM HOLDINGS, INC.',
 'INSPERITY, INC.',
 'HOSTESS BRANDS, INC.',
 'FIFTH THIRD BANCORP',
 'EMERGENT BIOSOLUTIONS INC.',
 'CDK GLOBAL, INC.',
 'DOLLAR TREE INC',
 'INNOVATIVE INDUSTRIAL PROPERTIES INC',
 'CLEARWATER PAPER CORP',
 'MGP INGREDIENTS INC',
 'NEOLEUKIN THERAPEUTICS, INC.',
 'CITIZENS FINANCIAL GROUP INC/RI',
 'SNAP-ON INC',
 'LAS VEGAS SANDS CORP',
 'EQT CORP',
 'COCA-COLA CONSOLIDATED, INC.',
 'DOUGLAS DYNAMICS, INC',
 'GARDNER DENVER HOLDINGS, INC.',
 'HORIZON GLOBAL CORP',
 'AIR PRODUCTS & CHEMICALS INC /DE/',
 'NEWPARK RESOURCES INC',
 'ABERDEEN STANDARD PLATINUM ETF TRUST',
 'RETAIL VALUE INC.',
 'EXELON CORP',
 'CAVENDISH FUTURES FUND LLC',
 'CHANNELADVISOR CORP',
 'COMPASS MINERALS INTERNATIONAL INC',
 'MONSTER BEVERAGE CORP',
 'BAY BANKS OF VIRGINIA INC',
 'ROLLINS INC',
 'TIMKEN CO',
 'COLONY CAPITAL, INC.',
 'RETAIL PROPERTIES OF AMERICA, INC.',
 'RING ENERGY, INC.',
 'FUELCELL ENERGY INC',
 'STRATTEC SECURITY CORP',
 'GENERAL DYNAMICS CORP',
 'NATURAL RESOURCE PARTNERS LP',
 'NORTHFIELD BANCORP, INC.',
 'UMPQUA HOLDINGS CORP',
 'JASON INDUSTRIES, INC.',
 'EAGLE PHARMACEUTICALS, INC.',
 'GREEN PLAINS INC.',
 'GRITSTONE ONCOLOGY, INC.',
 'KLDISCOVERY INC.',
 'CAPITAL BANCORP INC',
 'TENNESSEE VALLEY AUTHORITY',
 'COLE CREDIT PROPERTY TRUST V, INC.',
 'CSX CORP',
 'XCEL BRANDS, INC.',
 'POST HOLDINGS, INC.',
 'PLYMOUTH INDUSTRIAL REIT INC.',
 'NORTHWEST NATURAL HOLDING CO',
 'ULTRA CLEAN HOLDINGS, INC.',
 'PRIORITY TECHNOLOGY HOLDINGS, INC.',
 'J M SMUCKER CO',
 'WILLIAMS SONOMA INC',
 'CHAPARRAL ENERGY, INC.',
 'APTINYX INC.',
 'VERTIV HOLDINGS CO',
 'HANCOCK WHITNEY CORP',
 'UNION CARBIDE CORP /NEW/',
 'EVANS BANCORP INC',
 'NVIDIA CORP',
 'TEGNA INC',
 'DUKE REALTY CORP',
 'FABRINET',
 'DECIPHERA PHARMACEUTICALS, INC.',
 'BOYD GAMING CORP',
 'ROKU, INC',
 'COMMERCE BANCSHARES INC /MO/',
 'NEXPOINT RESIDENTIAL TRUST, INC.',
 'ARYA SCIENCES ACQUISITION CORP.',
 'LGI HOMES, INC.',
 'ILLINOIS TOOL WORKS INC',
 'NORTHERN OIL & GAS, INC.',
 'RED HAT INC',
 'BARNES GROUP INC',
 'TRINSEO S.A.',
 'BEL FUSE INC /NJ',
 'AVANTOR, INC.',
 'FAIR ISAAC CORP',
 'CBTX, INC.',
 'MCCORMICK & CO INC',
 'MMA CAPITAL HOLDINGS, INC.',
 'ACCELERATE DIAGNOSTICS, INC',
 'ORBCOMM INC.',
 'BROOKFIELD PROPERTY REIT INC.',
 'INTERPUBLIC GROUP OF COMPANIES, INC.',
 'AMCI ACQUISITION CORP.',
 'RHYTHM PHARMACEUTICALS, INC.',
 'SANDY SPRING BANCORP INC',
 'SIMON PROPERTY GROUP INC /DE/',
 'BALCHEM CORP',
 'WORTHINGTON INDUSTRIES INC',
 'LUBYS INC',
 'LONESTAR RESOURCES US INC.',
 'COMFORT SYSTEMS USA INC',
 'CC HOLDINGS GS V LLC',
 'APPLIED OPTOELECTRONICS, INC.',
 'TEJON RANCH CO',
 'WINDSTREAM HOLDINGS, INC.',
 'G III APPAREL GROUP LTD /DE/',
 'WHIRLPOOL CORP /DE/',
 'ZYLA LIFE SCIENCES',
 'DOCUSIGN INC',
 'AMERICAN SOFTWARE INC',
 'ABRAXAS PETROLEUM CORP',
 'KAR AUCTION SERVICES, INC.',
 'MATTHEWS INTERNATIONAL CORP',
 'RW HOLDINGS NNN REIT, INC.',
 'HILL-ROM HOLDINGS, INC.',
 'O-I GLASS, INC. /DE/',
 'GILEAD SCIENCES INC',
 'CSW INDUSTRIALS, INC.',
 'FRANKLIN FINANCIAL NETWORK INC.',
 'SOUTH DAKOTA SOYBEAN PROCESSORS LLC',
 'REPLIMUNE GROUP, INC.',
 'SLEEP NUMBER CORP',
 'BLUEPRINT MEDICINES CORP',
 'PROGRESSIVE CORP/OH/',
 'NORFOLK SOUTHERN CORP',
 'LEXICON PHARMACEUTICALS, INC.',
 'MAGNOLIA OIL & GAS CORP',
 'OMNOVA SOLUTIONS INC',
 'EAGLE FINANCIAL SERVICES INC',
 'ADDUS HOMECARE CORP',
 'PEGASYSTEMS INC',
 'EMMIS COMMUNICATIONS CORP',
 'PREVAIL THERAPEUTICS INC.',
 'UPLAND SOFTWARE, INC.',
 'EQUITY COMMONWEALTH',
 'FIDELITY NATIONAL INFORMATION SERVICES, INC.',
 'MARLIN BUSINESS SERVICES CORP',
 'RCI HOSPITALITY HOLDINGS, INC.',
 'COLGATE PALMOLIVE CO',
 'RITE AID CORP',
 'WINTRUST FINANCIAL CORP',
 'CHEESECAKE FACTORY INC',
 'FORTY SEVEN, INC.',
 'MGIC INVESTMENT CORP',
 'PERDOCEO EDUCATION CORP',
 'PROTEOSTASIS THERAPEUTICS, INC.',
 'BANK FIRST CORP',
 'GLOBAL PARTNERS LP',
 'NEW SENIOR INVESTMENT GROUP INC.',
 'ENNIS, INC.',
 'MERCK & CO., INC.',
 'W R GRACE & CO',
 'ATLANTIC CAPITAL BANCSHARES, INC.',
 'GENIE ENERGY LTD.',
 'OKLAHOMA GAS & ELECTRIC CO',
 'MYOKARDIA INC',
 'NEBULA ACQUISITION CORP',
 'BRISTOW GROUP INC',
 'SMARTSTOP SELF STORAGE REIT, INC.',
 'AMES NATIONAL CORP',
 "KIRKLAND'S, INC",
 'ISABELLA BANK CORP',
 'KRAFT HEINZ CO',
 'HALLMARK FINANCIAL SERVICES INC',
 'AMERICAN REALTY INVESTORS INC',
 'SKYWORKS SOLUTIONS INC',
 'AMERIS BANCORP',
 'ADVANSIX INC.',
 'PHILIP MORRIS INTERNATIONAL INC.',
 'TUSCAN HOLDINGS CORP. II',
 'MORGAN STANLEY',
 'CAROLINA FINANCIAL CORP',
 'CSB BANCORP INC /OH',
 'ON SEMICONDUCTOR CORP',
 'ANI PHARMACEUTICALS INC',
 'TOWNSQUARE MEDIA, INC.',
 'PIER 1 IMPORTS INC/DE',
 'FEDERAL HOME LOAN BANK OF TOPEKA',
 'ABBOTT LABORATORIES',
 'MSCI INC.',
 'ANSYS INC',
 'FINANCIAL INSTITUTIONS INC',
 'WEIS MARKETS INC',
 'DORIAN LPG LTD.',
 'PANGAEA LOGISTICS SOLUTIONS LTD.',
 'NATIONAL RETAIL PROPERTIES, INC.',
 'SPLUNK INC',
 'GUARANTY BANCSHARES INC /TX/',
 'FIRST FINANCIAL CORP /IN/',
 'J2 GLOBAL, INC.',
 'CUBIC CORP /DE/',
 'ALERUS FINANCIAL CORP',
 'BRT APARTMENTS CORP.',
 'APPLE HOSPITALITY REIT, INC.',
 'AMPHASTAR PHARMACEUTICALS, INC.',
 'CUMMINS INC',
 'CONOCOPHILLIPS',
 'RUBICON PROJECT, INC.',
 'JACK IN THE BOX INC /NEW/',
 'SESEN BIO, INC.',
 'AMERICAN INTERNATIONAL GROUP INC',
 'GIGCAPITAL2, INC.',
 'MASTEC INC',
 'TUESDAY MORNING CORP/DE',
 'NAVISTAR INTERNATIONAL CORP',
 'CARPENTER TECHNOLOGY CORP',
 'QUINSTREET, INC',
 'ZIX CORP',
 'VERACYTE, INC.',
 'SYSCO CORP',
 'PENNSYLVANIA REAL ESTATE INVESTMENT TRUST',
 'APPLIED MATERIALS INC /DE',
 'PREMIER, INC.',
 'SB FINANCIAL GROUP, INC.',
 'APACHE CORP',
 'PAYLOCITY HOLDING CORP',
 'VIRTUS INVESTMENT PARTNERS, INC.',
 'ODONATE THERAPEUTICS, INC.',
 'OHIO VALLEY BANC CORP',
 'TESLA, INC.',
 'EIDOS THERAPEUTICS, INC.',
 'GEOSPACE TECHNOLOGIES CORP',
 'SORRENTO THERAPEUTICS, INC.',
 'MCDERMOTT INTERNATIONAL INC',
 'STEWART INFORMATION SERVICES CORP',
 'ALBEMARLE CORP',
 'LIVE NATION ENTERTAINMENT, INC.',
 "SPORTSMAN'S WAREHOUSE HOLDINGS, INC.",
 'PROLOGIS, INC.',
 'EOG RESOURCES INC',
 'WEYCO GROUP INC',
 'CITIZENS FINANCIAL SERVICES INC',
 'INTUIT INC',
 'MYOVANT SCIENCES LTD.',
 'LIGHTSTONE VALUE PLUS REAL ESTATE INVESTMENT TRUST III, INC.',
 'LA-Z-BOY INC',
 'NORTHROP GRUMMAN CORP /DE/',
 'ESSA BANCORP, INC.',
 'TAUBMAN CENTERS INC',
 'TRONOX HOLDINGS PLC',
 'CHART INDUSTRIES INC',
 'CMS ENERGY CORP',
 'ELDORADO RESORTS, INC.',
 'BBX CAPITAL CORP',
 'CELANESE CORP',
 'G1 THERAPEUTICS, INC.',
 'OTELCO INC.',
 'CPI CARD GROUP INC.',
 'GRIFFIN-AMERICAN HEALTHCARE REIT IV, INC.',
 'EMBASSY BANCORP, INC.',
 'NMI HOLDINGS, INC.',
 'FULLER H B CO',
 'BAXTER INTERNATIONAL INC',
 'RH',
 '10X GENOMICS, INC.',
 'EQUINIX INC',
 'AVALARA, INC.',
 'ABERDEEN STANDARD SILVER ETF TRUST',
 'SIGMATRON INTERNATIONAL INC',
 'OLYMPIC STEEL INC',
 'UNION PACIFIC CORP',
 'BRIGHTSPHERE INVESTMENT GROUP INC.',
 'PAYPAL HOLDINGS, INC.',
 'GLOBAL EAGLE ENTERTAINMENT INC.',
 'HEXCEL CORP /DE/',
 'MICRON TECHNOLOGY INC',
 'RINGCENTRAL, INC.',
 'STEVEN MADDEN, LTD.',
 'MID PENN BANCORP INC',
 'PRGX GLOBAL, INC.',
 'BARNES & NOBLE INC',
 'BG STAFFING, INC.',
 'BLUEBIRD BIO, INC.',
 'RIMINI STREET, INC.',
 'II-VI INC',
 'BLACKROCK INC.',
 'INTREPID POTASH, INC.',
 'ISTAR INC.',
 'AMERICAN AXLE & MANUFACTURING HOLDINGS INC',
 'LOCKHEED MARTIN CORP',
 'FUTUREFUEL CORP.',
 'KAISER ALUMINUM CORP',
 'MAYVILLE ENGINEERING COMPANY, INC.',
 'NOBLE MIDSTREAM PARTNERS LP',
 'NEWMARKET CORP',
 'JONES LANG LASALLE INC',
 'CHATHAM LODGING TRUST',
 'COVIA HOLDINGS CORP',
 'CONSOL COAL RESOURCES LP',
 'LIGAND PHARMACEUTICALS INC',
 'RUMBLEON, INC.',
 'SUNSTONE HOTEL INVESTORS, INC.',
 'PANHANDLE EASTERN PIPE LINE COMPANY, LP',
 "BLOOMIN' BRANDS, INC.",
 'INSULET CORP',
 'SHOE CARNIVAL INC',
 'HARTE HANKS INC',
 'MEDTRONIC PLC',
 'DIME COMMUNITY BANCSHARES INC',
 'UNITY BIOTECHNOLOGY, INC.',
 'SIMMONS FIRST NATIONAL CORP',
 'UNIVAR SOLUTIONS INC.',
 'PENNS WOODS BANCORP INC',
 'GOLDFIELD CORP',
 'US ECOLOGY, INC.',
 'SABRA HEALTH CARE REIT, INC.',
 'PRICE T ROWE GROUP INC',
 'SCHWAB CHARLES CORP',
 'ASSOCIATED CAPITAL GROUP, INC.',
 'GREAT WESTERN BANCORP, INC.',
 'BLOOM ENERGY CORP',
 'PVH CORP. /DE/',
 "WENDY'S CO",
 'ENANTA PHARMACEUTICALS INC',
 'BLUE RIDGE BANKSHARES, INC.',
 'RESIDEO TECHNOLOGIES, INC.',
 'WATSCO INC',
 'BRIGHT HORIZONS FAMILY SOLUTIONS INC.',
 'GTT COMMUNICATIONS, INC.',
 'GOSSAMER BIO, INC.',
 'POWERFLEET, INC.',
 'TORO CO',
 'VORNADO REALTY TRUST',
 'COUNTY BANCORP, INC.',
 'NATIONAL HEALTH INVESTORS INC',
 'MSA SAFETY INC',
 'KENNEDY-WILSON HOLDINGS, INC.',
 'KIMBALL ELECTRONICS, INC.',
 'PUMA BIOTECHNOLOGY, INC.',
 'FIRST UNITED CORP/MD/',
 'PRECISION BIOSCIENCES INC',
 'CORNERSTONE BUILDING BRANDS, INC.',
 'ACI WORLDWIDE, INC.',
 'TRI-STATE GENERATION & TRANSMISSION ASSOCIATION, INC.',
 'GAIA, INC',
 'MSC INDUSTRIAL DIRECT CO INC',
 'HOULIHAN LOKEY, INC.',
 'REDWOOD MORTGAGE INVESTORS VIII',
 'MURPHY OIL CORP',
 'REGIS CORP',
 'SAVARA INC',
 'YRC WORLDWIDE INC.',
 'SOFTWARE ACQUISITION GROUP INC.',
 'SONOS INC',
 'WABCO HOLDINGS INC.',
 "AARON'S INC",
 'WYNDHAM HOTELS & RESORTS, INC.',
 'IDEANOMICS, INC.',
 'TRINET GROUP, INC.',
 'TOMPKINS FINANCIAL CORP',
 'ENPHASE ENERGY, INC.',
 'SWITCH, INC.',
 'J&J SNACK FOODS CORP',
 'FITBIT, INC.',
 'FIVE9, INC.',
 'ENLINK MIDSTREAM PARTNERS, LP',
 'SALESFORCE COM INC',
 'URBAN OUTFITTERS INC',
 'UNIVERSAL DISPLAY CORP PA',
 'BROWN & BROWN, INC.',
 'MYR GROUP INC.',
 'NORTHWEST PIPELINE LLC',
 'LANDSTAR SYSTEM INC',
 'PERKINELMER INC',
 'RICHMOND MUTUAL BANCORPORATION, INC.',
 'INSMED INC',
 'MACOM TECHNOLOGY SOLUTIONS HOLDINGS, INC.',
 'VEECO INSTRUMENTS INC',
 'MICHAELS COMPANIES, INC.',
 'COMPUTER TASK GROUP INC',
 'C & F FINANCIAL CORP',
 'GRAHAM CORP',
 'HORIZON BANCORP INC /IN/',
 'HSBC USA INC /MD/',
 'QWEST CORP',
 'CELLULAR BIOMEDICINE GROUP, INC.',
 'CENTENE CORP',
 'STAR GROUP, L.P.',
 'SALISBURY BANCORP INC',
 'PROSPER MARKETPLACE, INC',
 'TD AMERITRADE HOLDING CORP',
 'PLAINS ALL AMERICAN PIPELINE LP',
 'SYKES ENTERPRISES INC',
 'GCP APPLIED TECHNOLOGIES INC.',
 'TRIBUNE PUBLISHING CO',
 'CERIDIAN HCM HOLDING INC.',
 'KBS REAL ESTATE INVESTMENT TRUST III, INC.',
 'TURNING POINT THERAPEUTICS, INC.',
 'FRESHPET, INC.',
 'FUNKO, INC.',
 'PENNYMAC FINANCIAL SERVICES, INC.',
 'AEROCENTURY CORP',
 'CIT GROUP INC',
 'LIVONGO HEALTH, INC.',
 'RADIAN GROUP INC',
 'WASTE MANAGEMENT INC',
 'GRAPHIC PACKAGING HOLDING CO',
 'KKR & CO. INC.',
 'APOLLO COMMERCIAL REAL ESTATE FINANCE, INC.',
 'MIDWESTONE FINANCIAL GROUP, INC.',
 'SPOK HOLDINGS, INC',
 'OSHKOSH CORP',
 'SIMPLY GOOD FOODS CO',
 'SPANISH BROADCASTING SYSTEM INC',
 'INDEPENDENCE CONTRACT DRILLING, INC.',
 'TECTONIC FINANCIAL, INC.',
 'PARKE BANCORP, INC.',
 'IHEARTMEDIA, INC.',
 'WESCO AIRCRAFT HOLDINGS, INC',
 'NAUTILUS, INC.',
 'PLAYAGS, INC.',
 'SURMODICS INC',
 'CATALYST BIOSCIENCES, INC.',
 'SYNEOS HEALTH, INC.',
 'SEQUENTIAL BRANDS GROUP, INC.',
 'JOHNSON & JOHNSON',
 'ALLIANT ENERGY CORP',
 'BENEFITFOCUS,INC.',
 'EQUITABLE HOLDINGS, INC.',
 'CHEMED CORP',
 'KOSMOS ENERGY LTD.',
 'WESTROCK CO',
 'EXPERIENCE INVESTMENT CORP.',
 'ALTRIA GROUP, INC.',
 'CORNING INC /NY',
 'AUTONATION, INC.',
 'CULLEN/FROST BANKERS, INC.',
 'NCL CORP LTD.',
 'VERICEL CORP',
 'AKEBIA THERAPEUTICS, INC.',
 'EASTGROUP PROPERTIES INC',
 'HELIX ENERGY SOLUTIONS GROUP INC',
 'MIDDLESEX WATER CO',
 'ALTERYX, INC.',
 'MARTIN MIDSTREAM PARTNERS L.P.',
 'CAVCO INDUSTRIES INC.',
 'PROCTER & GAMBLE CO',
 'BRAEMAR HOTELS & RESORTS INC.',
 'LUMENTUM HOLDINGS INC.',
 'JUNIATA VALLEY FINANCIAL CORP',
 'ELANCO ANIMAL HEALTH INC',
 'AVON PRODUCTS INC',
 'VERISK ANALYTICS, INC.',
 'ALPHATEC HOLDINGS, INC.',
 'ENOVA INTERNATIONAL, INC.',
 'LEXINGTON REALTY TRUST',
 'MOHAWK INDUSTRIES INC',
 'CLARUS CORP',
 'BEAZER HOMES USA INC',
 'DEERE & CO',
 'CONSUMER PORTFOLIO SERVICES INC',
 'QORVO, INC.',
 'ENTRAVISION COMMUNICATIONS CORP',
 'REPUBLIC SERVICES, INC.',
 'WINDTREE THERAPEUTICS INC /DE/',
 'FS CREDIT REAL ESTATE INCOME TRUST, INC.',
 'PAE INC',
 'PROGENICS PHARMACEUTICALS INC',
 'ABERDEEN STANDARD PRECIOUS METALS BASKET ETF TRUST',
 'FRP HOLDINGS, INC.',
 'SHELL MIDSTREAM PARTNERS, L.P.',
 'ZILLOW GROUP, INC.',
 'HAWTHORN BANCSHARES, INC.',
 'MASCO CORP /DE/',
 'NATUS MEDICAL INC',
 'WORLD GOLD TRUST',
 'NORTHRIM BANCORP INC',
 'MINERVA NEUROSCIENCES, INC.',

In [45]:
#brd_list
brd_labels = pd.read_excel('debtor_list_ein_lookup.xlsx', sheet_name='LIST_2020_2')
brd_labels.head()

,debtor_name,date_filed,chapter_filing,name_in_sec_data,Unnamed: 4,Unnamed: 5
0,"AAC Holdings, Inc.",2020-06-20,Chapter 11,"AAC HOLDINGS, INC.",NaN,NaN
1,"Akorn, Inc.",2020-05-20,Chapter 11,AKORN INC,NaN,NaN
2,"Ascena Retail Group, Inc.",2020-07-23,Chapter 11,"ASCENA RETAIL GROUP, INC.",NaN,NaN
3,Briggs & Stratton Corporation,2020-07-20,Chapter 11,BRIGGS & STRATTON CORP,NaN,NaN
4,California Resources Corporation,2020-07-15,Chapter 11,CALIFORNIA RESOURCES CORP,NaN,NaN

In [46]:
#capitalize 
brd_labels['company_name_brd'] = brd_labels['name_in_sec_data'].str.upper()
brd_labels.head()

,debtor_name,date_filed,chapter_filing,name_in_sec_data,Unnamed: 4,Unnamed: 5,company_name_brd
0,"AAC Holdings, Inc.",2020-06-20,Chapter 11,"AAC HOLDINGS, INC.",NaN,NaN,"AAC HOLDINGS, INC."
1,"Akorn, Inc.",2020-05-20,Chapter 11,AKORN INC,NaN,NaN,AKORN INC
2,"Ascena Retail Group, Inc.",2020-07-23,Chapter 11,"ASCENA RETAIL GROUP, INC.",NaN,NaN,"ASCENA RETAIL GROUP, INC."
3,Briggs & Stratton Corporation,2020-07-20,Chapter 11,BRIGGS & STRATTON CORP,NaN,NaN,BRIGGS & STRATTON CORP
4,California Resources Corporation,2020-07-15,Chapter 11,CALIFORNIA RESOURCES CORP,NaN,NaN,CALIFORNIA RESOURCES CORP

In [47]:
brd_names = set(brd_labels['company_name_brd'])
brd_names

{'AAC HOLDINGS, INC.',
 'AKORN INC',
 'ASCENA RETAIL GROUP, INC.',
 'BRIGGS & STRATTON CORP',
 'CALIFORNIA RESOURCES CORP',
 'CARBO CERAMICS INC',
 'CBL & ASSOCIATES PROPERTIES INC',
 'CEC ENTERTAINMENT INC',
 'CENTRIC BRANDS INC.',
 'CHAPARRAL ENERGY, INC.',
 'CHESAPEAKE ENERGY CORP',
 'COVIA HOLDINGS CORP',
 'DENBURY RESOURCES INC',
 'DIAMOND OFFSHORE DRILLING, INC.',
 'EXTRACTION OIL & GAS, INC.',
 'FORESIGHT ENERGY LP',
 'FRONTIER COMMUNICATIONS CORP',
 'FTS INTERNATIONAL, INC.',
 'GLOBAL EAGLE ENTERTAINMENT INC.',
 'GNC HOLDINGS, INC.',
 'GULFPORT ENERGY CORP',
 'HERTZ CORP',
 'HERTZ GLOBAL HOLDINGS INC',
 'HERTZ GLOBAL HOLDINGS, INC',
 'HI-CRUSH INC.',
 'HORNBECK OFFSHORE SERVICES INC /LA',
 'INTERNAP CORP',
 'J C PENNEY CO INC',
 'J CREW GROUP INC',
 'JASON INDUSTRIES, INC.',
 'LIBBEY INC',
 'LONESTAR RESOURCES US INC.',
 'LSC COMMUNICATIONS, INC.',
 'MCCLATCHY CO',
 'MCDERMOTT INTERNATIONAL INC',
 'NEIMAN MARCUS GROUP LTD LLC',
 'OASIS PETROLEUM INC.',
 'PENNSYLVANIA REAL ESTATE INVESTMENT TRUST',
 'PIER 1 IMPORTS INC/DE',
 'PIONEER ENERGY SERVICES CORP',
 'PYXUS INTERNATIONAL, INC.',
 'QUORUM HEALTH CORP',
 'ROSEHILL RESOURCES INC.',
 'RTW RETAILWINDS, INC.',
 'STAGE STORES INC',
 'STEIN MART INC',
 'SUPERIOR ENERGY SERVICES INC',
 'TAILORED BRANDS INC',
 'TOWN SPORTS INTERNATIONAL HOLDINGS INC',
 'TUESDAY MORNING CORP/DE',
 'ULTRA PETROLEUM CORP',
 'UNIT CORP',
 'WHITING PETROLEUM CORP'}

In [48]:
# compare the two sets 

brd_names.difference(company_unique)

{'AAC HOLDINGS, INC.',
 'CENTRIC BRANDS INC.',
 'HERTZ CORP',
 'HERTZ GLOBAL HOLDINGS INC',
 'NEIMAN MARCUS GROUP LTD LLC'}

In [ ]:
### Have notes in word doc.  these are okay

In [35]:
query = """
SELECT distinct company_name, period_end_date
FROM sec_prep_2019
WHERE  company_name LIKE '%DIAMOND%'
;
"""

one_company = pd_sql.read_sql(query, connection)
one_company

                          company_name period_end_date
0     BLACK DIAMOND THERAPEUTICS, INC.      2019-12-31
1  DIAMOND EAGLE ACQUISITION CORP.  DE      2019-12-31
2    DIAMOND HILL INVESTMENT GROUP INC      2019-12-31
3      DIAMOND OFFSHORE DRILLING, INC.      2019-12-31
4              DIAMOND S SHIPPING INC.      2019-12-31
5             DIAMONDBACK ENERGY, INC.      2019-12-31
6           DIAMONDPEAK HOLDINGS CORP.      2019-12-31
7           DIAMONDROCK HOSPITALITY CO      2019-12-31

In [31]:
query = """
SELECT distinct company_name
FROM sec_all_raw
WHERE  company_name LIKE '%HI-%'
;
"""

one_company = pd_sql.read_sql(query, connection)
one_company

           company_name
0  HI-CRUSH PARTNERS LP

In [11]:
query = """
SELECT distinct company_name, period_end_date
FROM sec_all_raw
WHERE  company_name LIKE '%ASCENA RETAIL GROUP, INC.%'
;
"""

one_company = pd_sql.read_sql(query, connection)
one_company

                company_name period_end_date
0  ASCENA RETAIL GROUP, INC.      2011-07-31
1  ASCENA RETAIL GROUP, INC.      2012-07-31
2  ASCENA RETAIL GROUP, INC.      2013-07-31
3  ASCENA RETAIL GROUP, INC.      2014-07-31
4  ASCENA RETAIL GROUP, INC.      2015-07-31
5  ASCENA RETAIL GROUP, INC.      2016-07-31
6  ASCENA RETAIL GROUP, INC.      2017-07-31
7  ASCENA RETAIL GROUP, INC.      2018-07-31

In [12]:

query = """
SELECT distinct company_name, form, number_of_quarters, period_end_date
FROM sec_raw_all
WHERE  company_name LIKE '%CENTRIC BRANDS INC.'
;
"""

one_company = pd_sql.read_sql(query, connection)
one_company

          company_name  form  number_of_quarters period_end_date
0  CENTRIC BRANDS INC.  10-K                   0      2016-12-31
1  CENTRIC BRANDS INC.  10-K                   0      2017-12-31
2  CENTRIC BRANDS INC.  10-K                   0      2018-12-31
3  CENTRIC BRANDS INC.  10-K                   4      2017-12-31
4  CENTRIC BRANDS INC.  10-K                   4      2018-12-31

In [57]:

query = """
SELECT distinct company_name, form, number_of_quarters, period_end_date
FROM sec_raw_all
WHERE  period_end_date < '2019-01-01' 
    and company_name LIKE '%SUNEDISON, INC%'
;
"""

one_company = pd_sql.read_sql(query, connection)
one_company

# bankruptcy 4/21/2016
# have 10-Q 	2015-09-30

      company_name  form  number_of_quarters period_end_date
0  SUNEDISON, INC.  10-K                   0      2010-12-31
1  SUNEDISON, INC.  10-K                   0      2011-12-31
2  SUNEDISON, INC.  10-K                   0      2012-12-31
3  SUNEDISON, INC.  10-K                   0      2013-12-31
4  SUNEDISON, INC.  10-K                   0      2014-12-31
5  SUNEDISON, INC.  10-K                   4      2011-12-31
6  SUNEDISON, INC.  10-K                   4      2012-12-31
7  SUNEDISON, INC.  10-K                   4      2013-12-31
8  SUNEDISON, INC.  10-K                   4      2014-12-31

In [76]:

query = """
SELECT distinct company_name, form, number_of_quarters, period_end_date
FROM sec_raw_all
WHERE  period_end_date < '2019-01-01' 
    and company_name LIKE '%VENOCO%'
;
"""

one_company = pd_sql.read_sql(query, connection)
one_company
#bankruptcy 3/18/2016  - some filings are VENOCO other filings are DENVER PARENT CORP
#BRD list has Venoco, Inc. (Denver Parent Corp.)

    company_name  form  number_of_quarters period_end_date
0   VENOCO, INC.  10-K                   0      2010-12-31
1   VENOCO, INC.  10-K                   0      2011-12-31
2   VENOCO, INC.  10-K                   0      2012-12-31
3   VENOCO, INC.  10-K                   0      2013-12-31
4   VENOCO, INC.  10-K                   1      2012-03-31
5   VENOCO, INC.  10-K                   1      2012-06-30
6   VENOCO, INC.  10-K                   1      2012-09-30
7   VENOCO, INC.  10-K                   1      2012-12-31
8   VENOCO, INC.  10-K                   1      2013-03-31
9   VENOCO, INC.  10-K                   1      2013-06-30
10  VENOCO, INC.  10-K                   1      2013-09-30
11  VENOCO, INC.  10-K                   1      2013-12-31
12  VENOCO, INC.  10-K                   4      2011-12-31
13  VENOCO, INC.  10-K                   4      2012-12-31
14  VENOCO, INC.  10-K                   4      2013-12-31

In [75]:

query = """
SELECT distinct company_name, form, number_of_quarters, period_end_date
FROM sec_raw_all
WHERE  period_end_date < '2019-01-01' 
    and company_name LIKE '%DENVER PARENT%'
;
"""

one_company = pd_sql.read_sql(query, connection)
one_company
 #bankruptcy 3/18/2016  - some filings are VENOCO

          company_name  form  number_of_quarters period_end_date
0   DENVER PARENT CORP  10-K                   0      2011-12-31
1   DENVER PARENT CORP  10-K                   0      2012-12-31
2   DENVER PARENT CORP  10-K                   0      2013-12-31
3   DENVER PARENT CORP  10-K                   0      2014-12-31
4   DENVER PARENT CORP  10-K                   0      2015-12-31
5   DENVER PARENT CORP  10-K                   1      2013-03-31
6   DENVER PARENT CORP  10-K                   1      2013-06-30
7   DENVER PARENT CORP  10-K                   1      2013-09-30
8   DENVER PARENT CORP  10-K                   1      2013-12-31
9   DENVER PARENT CORP  10-K                   1      2014-03-31
10  DENVER PARENT CORP  10-K                   1      2014-06-30
11  DENVER PARENT CORP  10-K                   1      2014-09-30
12  DENVER PARENT CORP  10-K                   1      2014-12-31
13  DENVER PARENT CORP  10-K                   1      2015-03-31
14  DENVER PARENT CORP  10-K                   1      2015-06-30
15  DENVER PARENT CORP  10-K                   1      2015-09-30
16  DENVER PARENT CORP  10-K                   1      2015-12-31
17  DENVER PARENT CORP  10-K                   4      2012-12-31
18  DENVER PARENT CORP  10-K                   4      2013-12-31
19  DENVER PARENT CORP  10-K                   4      2014-12-31
20  DENVER PARENT CORP  10-K                   4      2015-12-31